include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: 3754b1d9e97e8aee8eb3074e78a5f92dc8220132
    file: ci/default.yml

variables:
  PYTEST_COV_FAIL_UNDER: 0  # Set pytest coverage to 0
  DEBUG: "2"                  # Set debug mode to print out executed command on qa-ci
  PYVER: "3.9"
  APT_INSTALL: "build-essential"
  PUBLISH_POETRY: "true"  # Set to true to allow CI to publish package to PYPI
